import * as vite from 'npm:vite@5.3.3'
import * as fs from 'jsr:@std/fs@1.0.5'
import * as path from 'jsr:@std/path@1.0.7'
import * as enc from 'jsr:@std/encoding@1.0.1'

export function createMemoryAssets(files: {name:string, path:string}[], assetsFile: string, reader?: (f: typeof files[0]) => Uint8Array|null) {
  const assetsLines = files.map(f => `  "${f.name}": "${enc.encodeBase64(reader?.(f) || Deno.readFileSync(f.path))}"`)
  const comment = `// This file is generated by build.ts. Do not edit it manually.\n// It contains the base64 encoded content of the files in the sample app, which will be used to create the bootstrap files when running 'create-app' command.\n`
  const assetsTs = `${comment}\nexport const assets: Record<string, string> = {\n${assetsLines.join(',\n')}\n}\n`
  Deno.writeTextFileSync(assetsFile, assetsTs)
}

export function saveMemoryAssets(assets: Record<string, string>, root: string) {
  for (const [name, data] of Object.entries(assets)) {
    const filePath = root + '/' + name
    fs.ensureDirSync(path.dirname(filePath))
    Deno.writeFileSync(filePath, enc.decodeBase64(data))
  }
}

export async function buildViteDistAsMemoryAssets(root: string, assetsFile: string) {
    const r = await vite.build({
        root,
        build: {
            rollupOptions: {
              output: {
                entryFileNames: `[name].js`,
                chunkFileNames: `[name].js`,
                assetFileNames: `[name].[ext]`
              }
            }
          }
    })

    const files = fs.expandGlobSync('**/*', { root: root + '/dist', includeDirs: false})
    createMemoryAssets([...files], assetsFile)
}
